### ISSUE TITLE
Needs to be completed

### ISSUE THREAD

**Issue by aviflombaum** [learn-co-curriculum/ruby-boolean-enumerables#1]
Outline https://github.com/learn-co-curriculum/ruby-boolean-enumerables/blob/master/README.md

**Comment by aviflombaum** [comment]
@SophieDeBenedetto I'll do this.

**Comment by SophieDeBenedetto** [comment]
@aviflombaum it might be the case that Ian has started working on this. you might want to check w him

**Comment by aviflombaum** [comment]
I just finished it - will ping him. Thanks for the heads up.
