### ISSUE TITLE
Issue with 2 tests in play_spec.rb

### ISSUE THREAD

**Issue by azheng249** [learn-co-curriculum/ruby-boolean-enumerables#10]
The tests "checks if the game is won after every turn" and "checks if the game is draw after every turn" seem to make rspec break and not finish. They both have "allow(self).to receive(:gets).and_return("1", "2", "3")" which should put in 1, 2 and 3 as the inputs. 

But below the tests say, "expect(self).to receive(:won?).at_least(:twice).and_return(false, false, true)" and "expect(self).to receive(:draw?).at_least(:twice).and_return(false, false, true)".

The tests are expecting win? and draw? to be true on the third try, but this would be false since the board will look like:
##  X | O | X 

```
|      |
```

---

```
|      |
```

I have run my #play method in the console several times and it seems recognize all draws and wins(vertical, horizontal, diagonal). However when I run learn in the terminal, RSpec seems to break when it checks if a game is won after a turn. I think the test should expect (false, false, false) if I'm not mistaken.

**Comment by AnnJohn** [comment]
Hi @azheng249 it looks like the issue you raised is for a different lesson that this one.  Could you please let us know which lesson this issue belongs to or add it there yourself if you can? Thanks!

**Comment by azheng249** [comment]
Sorry, I was doing a later lesson and clicked back to this as reference. I had issues with the lab on the lesson, TicTacToe.Rb. Inside the spec folder there is a spec, 02_play_spec.rb. The 2 tests I was referring to are on lines 47-66.

When I do the lab in Nitrous and run my TicTacToe program in the Nitrous console, it runs like you would expect the game to run. It welcomes the player and runs until it finds a winning combination or the board is full and is a draw. It then congratulates the winner or prints 'Cats Game!'. 

I followed the README's instructions but when I run 'learn' in the console, it passes every other test only to pause at the "checks if the game is won after every turn" test. It is stuck in an infinite loop and the only way I finished my lab was putting an if statement in my play method to break if winner(board) returned 'X' or 'O'. I did this after seeing line 51 in 02_play_spec.rb. Without this my code would never finish checking and RSpec keeps running until it crashes my computer or I close the console.

https://github.com/learn-co-curriculum/tic-tac-toe-rb/issues

In the issues page, there are 2 others that mention the errors I had when trying to finish the lab. One guy also got an infinite loop and another guy had the 'StackLevel Too Deep' error I got early in the lab.

**Comment by AnnJohn** [comment]
Hi @azheng249 thanks for raising this issue. Yes, definitely aware of the infinite loops problem on the lab. We're going to have a fix for it soon, but in the meantime, please use the Ask a Question tool and one of our Learn Experts will be able to help you right away.
