### ISSUE TITLE
#include? description of example doesn't match example

### ISSUE THREAD

**Issue by michaelsimon** [learn-co-curriculum/ruby-boolean-enumerables#11]
The last sentence in the lesson describing how #include? works does not seem to match the code example that is above it. If not meant to describe that code block, may need to be reworded.

**Comment by AnnJohn** [comment]
Hi @michaelsimon the last sentence actually does reference the code block above. the_numbers[5] == 42 means that the fifth index here is 42 and so the #include? will return true because 42 is an element in the array. 

Thanks!
